[package]
authors = ["Vinzent Steinberg <Vinzent.Steinberg@gmail.com>"]
name = "sample-sphere"
version = "0.1.0"

[dependencies]
rand = "0.4"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "basic"
harness = false
