[package]
authors = ["Vinzent Steinberg <Vinzent.Steinberg@gmail.com>"]
license = "MIT/Apache-2.0"
name = "sample-sphere"
version = "0.1.0"

[[bench]]
harness = false
name = "basic"

[dependencies]
rand = "0.5"

[dev-dependencies]
criterion = "0.2"
